# Site settings
title: My Jekyll Blog
email: your-email@example.com
description: A minimal Jekyll blog hosted on Vercel
baseurl: "" 
url: "" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore