# Site settings
title: My Jekyll Blog
email: your-email@example.com
description: A minimal Jekyll blog hosted on Vercel
baseurl: "" 
url: "https://charlje.vercel.app" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for tags
collections:
  tags:
    output: true
    permalink: /tags/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore