# Site settings
title: Charlie Davidmann
email: your-email@example.com
description: Personal blog of Charlie Davidmann
baseurl: "" 
url: "https://charlje.vercel.app" 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for themes
collections:
  themes:
    output: true
    permalink: /themes/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore